export type TruthState =
  | "RAW"
  | "STRUCTURED"
  | "CANDIDATE"
  | "VALIDATED"
  | "CONFLICTED"
  | "REJECTED"
  | "SUPERSEDED";

export type WarningCode =
  | "MISSING_PROVENANCE"
  | "MISSING_DATA"
  | "LOW_CONFIDENCE"
  | "CONFLICT_DETECTED"
  | "OPINION_DETECTED"
  | "RECOMMENDATION_DETECTED"
  | "AI_EXTRACTION_LIMIT"
  | "SINGLE_SOURCE_LIMIT"
  | "PROMPT_INJECTION_DETECTED"
  | "UNSAFE_INPUT";

export type FailureCode =
  | "INVALID_INPUT"
  | "BOUNDARY_VIOLATION"
  | "DOCTRINE_VIOLATION"
  | "UNSUPPORTED_TRUTH"
  | "SCHEMA_ERROR"
  | "SECURITY_REJECTION";
